- name: make static directory world writable XXX
  become: yes
  file:
    group: www-data
    mode: u=rwx,g=rwx,o=rwx
    owner: www-data
    path: "{{ static_dir }}"
    state: directory

- name: Look up user id of project user
  getent:
    database: passwd
    key: "{{ project_user }}"

- set_fact:
    project_user_id: "{{ getent_passwd[project_user][1] }}"
    project_group_id: "{{ getent_passwd[project_user][2] }}"

- name: manage.py collectstatic
  docker_container:
    cleanup: true
    command: "./manage.py collectstatic --no-input --clear"
    detach: false
    env: "{{ docker_env }}"
    image: "{{ image_registry_url }}"
    name: django_collectstatic
    network_mode: host
    restart_policy: no
    state: started
    volumes: "{{ docker_volumes }}"
    user: "{{ project_user_id }}:{{ project_group_id }}"
