- name: Get ECR token
  shell: "aws ecr get-login-password --region {{ aws_region }}"
  register: ecr_token
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ECR_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_ECR_SECRET_ACCESS_KEY }}"

- name: Log into ECR registry
  docker_login:
    registry_url: "{{ image_registry_url }}"
    debug: yes
    username: "AWS"
    password: "{{ ecr_token.stdout }}"
    reauthorize: yes

- name: Pull an image
  community.docker.docker_image:
    name: "{{ image_registry_url }}"
    force_source: true
    source: pull
    tag: latest
