- name: Look up user id of project user
  getent:
    database: passwd
    key: "{{ project_user }}"

- set_fact:
    project_user_id: "{{ getent_passwd[project_user][1] }}"
    project_group_id: "{{ getent_passwd[project_user][2] }}"

- name: Start container
  docker_container:
    env: "{{ docker_env }}"
    image: "{{ image_registry_url }}"
    name: django_application
    network_mode: host
    restart_policy: unless-stopped
    state: started
    volumes: "{{ docker_volumes }}"
    user: "{{ project_user_id }}:{{ project_group_id }}"
    log_driver: syslog
    log_options:
      syslog-address: unixgram:///dev/log
      syslog-facility: daemon
      tag: "{{ project_name }}"
